### ISSUE TITLE
no file to put api key to

### ISSUE THREAD

**Issue by BarKooo** [akshatmittal/youtube-realtime#32]
i can't find the file where i should put api key to

**Comment by CybermindDBS** [comment]
It should be in Index.html file.

**Comment by BarKooo** [comment]
i can't find it using ctrl+f

**Comment by akshatmittal** [comment]
I switched it to use a custom API instead of leaking the API Keys in the source code. You can still clone/lookup the previous code here: https://github.com/akshatmittal/youtube-realtime/tree/c5689a03ba18e12b9eb3588b392db9f2af7b69bd

You'll find the place for API Keys here: https://github.com/akshatmittal/youtube-realtime/blob/c5689a03ba18e12b9eb3588b392db9f2af7b69bd/assets/js/keyManager.js#L2
