### ISSUE TITLE
YouTube vanity names

### ISSUE THREAD

**Issue by petertenhoor** [akshatmittal/youtube-realtime#5]
Hi Akshat,

Nice to see that channel ID's work now!

Do you by any chance see the possibility to also make your counter work with a YouTube channel name instead of of the channel username?

Example: A youtuber has the channelname 'FCroelie'. When I enter his channelname in the URL (youtube.com/fcroelie) it opens his channel because it is redirected to his YouTube ID channel URL (https://www.youtube.com/channel/UCg0G6cfC6FH4u9yW3y-LUZQ). 

It does work to enter his channel ID in your application, but when I enter 'FCRoelie' it does not return any values but zero's.

Perhaps the code of this livecounter might help: http://livecounts.t15.org/?channel=fcroelie

Greetings,

Peter

**Comment by akshatmittal** [comment]
Hi Peter,

What you described for 'FCroelie' are vanity links, I'm currently trying to get this to work with this but  YouTube does not have an API to query users by vanity names. (Also check #1)

The other live counts link you gave me runs part of the code on the backend, which is not possible here since this is pure frontend code. I will try to implement a temporary fix for vanity urls this week, but can not say for sure.

You can simply use the channel ID (In this case: [UCg0G6cfC6FH4u9yW3y-LUZQ](https://akshatmittal.github.io/youtube-realtime/#!/UCg0G6cfC6FH4u9yW3y-LUZQ)) to view the live counts till then.

Greetings,
Akshat Mittal

**Comment by petertenhoor** [comment]
Awesome man, I will use channel ID's for now and keep checking your repository for updates.

Best regards,

Peter

**Comment by petertenhoor** [comment]
Hi Akshat,

I am getting near to a solution for the vanity names and would like to share my idea with you. 

Using the YouTube search API like this will get you a list of channels and their corresponding data, where the first item is the channel you need:

https://www.googleapis.com/youtube/v3/search?part=snippet&q=[vanity name]&type=channel&key=[apikey]

If you parse the YouTube Channel ID in the first item of that JSON call, you can use that value for the variable 'username'.

Let me know what you think! :)

Greetings,

Peter

**Comment by akshatmittal** [comment]
I just pushed a new version of YouTube Realtime which implements vanity URLs as well! :)

Have fun!

---

Commit: https://github.com/akshatmittal/youtube-realtime/commit/be4fba9e576e8a5150d7a5e9983f84529a520d9f

**Comment by petertenhoor** [comment]
Amazing work!
